version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

sphinx:
  configuration: doc/conf.py

formats: all

submodules:
  include: all
  recursive: true

python:
  install:
    - requirements: doc/requirements-rtd.txt
